name: Check Process

on:
  # main ブランチ への Pull Request を対象にする
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Flutter Lints
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Flutter SDKをセットアップ
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 必要なパッケージをインストール
      - name: Install dependencies
        run: flutter pub get

      # flutter analyze を実行し、結果をログに出力
      - name: Run Flutter Analyze
        run: |
          flutter analyze --no-pub > lint-report.txt || true

      # Lintエラーがある場合にPRコメントを投稿
      - name: Post Lint Results to PR
        if: always() # 常に実行（lintのエラーがあっても実行するため）
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # issueがあるか確認
          if grep -qE 'info|error|warning' lint-report.txt; then
            # 結果を整形してコメント用に保存
            echo "### Flutter Lint Results" > comment.md
            echo '```' >> comment.md
            cat lint-report.txt >> comment.md
            echo '```' >> comment.md

            # PRにコメントを投稿
            gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md

            # CIを失敗させる
            exit 1
          fi
